### ISSUE TITLE
关于验证器的一点建议

### ISSUE THREAD

**Issue by CyberLife-Markus** [top-think/think-validate#3]
前提：并不是在TP框架里使用该扩展...
1.在配置里是否应该应该增加抛出异常的配置，目前check后只返回bool，每次判断都需要if判断一下，没办法直接捕获异常输出信息。
`        if ($check !== true){
            return json_encode(['code'=>0,'msg'=>$validate->getError()]);
        }`
2.在实际使用中，发现更希望验证器去完成[数据格式化]的工作，当客户端传递[a,b,c]三个参数进来之后，丢进验证器进行对应的场景验证后，实际业务只需要[a,c]两个参数，所以希望验证器经过场景验证后返回的数据应该是['status'=>true,'data'=>[a,c]],而不是只返回一个bool来判断，把$_POST再放到控制器或者model里边去筛选剔除不需要或者会导致异常的额外参数。

**Comment by liu21st** [comment]
后续版本考虑改进下 但验证操作本身不适合涉及修改操作 这个之前也讨论过很多此 极容易混淆，数据不知不觉的修改却不知道哪里改的

**Comment by CyberLife-Markus** [comment]
嗯嗯，也许在Request类里做这个事会清晰些。感谢回复
