### ISSUE TITLE
场景验证方法bug

### ISSUE THREAD

**Issue by cpj555** [top-think/think-validate#4]
![image](https://user-images.githubusercontent.com/19289096/49784190-5e3f7800-fd57-11e8-8509-3c5936c0de66.png)
![image](https://user-images.githubusercontent.com/19289096/49784203-68fa0d00-fd57-11e8-8634-d1c51869613b.png)

对比了下框架里面的验证类和composer包拉出来的验证类 发现这个checkItem有改动没有更新？
框架里验证类场景验证是可以用的

**Comment by liu21st** [comment]
嗯 没有及时同步
